export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const SET_REVIEWS_LIST = 'SET_REVIEWS_LISTS';
export const SET_ORIGINAL_REVIEWS_LIST = 'SET_ORIGINAL_REVIEWS_LIST';
export const VOTE_REVIEW = 'VOTE_REVIEW';
export const REPLY_REVIEW = 'REPLY_REVIEW';
export const SET_IS_FILTERING_REVIEWS = 'SET_IS_FILTERING_REVIEWS';
export const FILTER_REVIEWS = 'FILTER_REVIEWS';
